### ISSUE TITLE
Dashboard Dimmer does not cover the whole screen

### ISSUE THREAD

**Issue by TerraXD** [CriticalFlaw/flawhud#100]
So I have A [Bug At The Main Menu](https://imgur.com/a/PfTqG85) And It  ticks me off a little. Can Someone Help me ?
![flaawhud](https://user-images.githubusercontent.com/63020964/88577723-c5eb2980-d047-11ea-8b19-010fcc16db15.PNG)

**Comment by CriticalFlaw** [comment]
If you're referring to the dashboard dimmer not stretching across the whole screen, I understand. It's an issue with multiple HUDs because the dimmer is hard-coded and cannot be removed by conventional means.

It is possible to remove it with a configuration script but what that does is disable the ability to close the dashboard by clicking anywhere on the screen. That's why I had to revert the change and restore the dimmer because a lot of users encountered that issue.

**Comment by TerraXD** [comment]
okay. have a Good Day !
