### ISSUE TITLE
Weapon skins all look squished

### ISSUE THREAD

**Issue by spell-bound** [CriticalFlaw/flawhud#130]
![20201013111330_1](https://user-images.githubusercontent.com/72820062/95899479-7ca49f00-0d45-11eb-9f76-2cff86268dc7.jpg)
Also if you could add player models to the scoreboard thatd be cool. Love this hud!

**Comment by h9lk** [comment]
some weird aspect ratio, it seemed to me that everyone use same weapon models in hud, don't they?

![20201014222705_1](https://user-images.githubusercontent.com/32390006/96036255-e075b780-0e6c-11eb-904b-b91ffa30aac7.jpg)

**Comment by CriticalFlaw** [comment]
Lower resolutions will squish on screen elements together. That's why there's no gap between the dashboard and the Loadout/Stat tabs in the first screenshot.

The optimal resolution, the one FlawHUD was made for is 16:9 at 1920x1080 anything lower or higher may yield mixed results not all of which, such as the the skins, can be fixed.

**Comment by spell-bound** [comment]
Oh okay switching from 2560x1440 to 1080 fixed it thanks
