### ISSUE TITLE
Add DashboardDimmer support

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#132]
It's bad to have it off since it can cause problems. But is ugly to have it on and not use it the "correct" way.
ToonHUD, for example, was designed in a way that it perfectly fits the DashboardDimmer.

**Can't you do the same, CriticalFlaw?**

**Comment by CriticalFlaw** [comment]
This would necessitate a main menu redesign. My reasoning against the idea is that the DashboardDimmer is only an issue when the Matchmaking Menu is open. To workaround it and have a persistent menu at the bottom of the screen is not ideal because: 

1. It would cut off a portion of the background, which would always look bad and require that to be changed as well.
2. The menu has very few options available, that means either everything or most of them would need to be on the bottom menu. In case of the former, it will look too cluttered and in the latter, lot of space won't be filled and the remaining few options would just hang on the middle of the screen and look weird.
3. Lot of the ideal designs are already used by other HUDs and I don't want to borrow from them for this one small issue.
