### ISSUE TITLE
How to enable the default floating health cross?

### ISSUE THREAD

**Issue by johnRivs** [CriticalFlaw/flawhud#144]
This one.
![](https://i.imgur.com/dmcR7AG.png)

**Comment by h9lk** [comment]
Why is this display inconvenient? 
![20210124220409_1](https://user-images.githubusercontent.com/32390006/105640818-293c0400-5e91-11eb-8665-35306fa3c80a.jpg)
![20210124220420_1](https://user-images.githubusercontent.com/32390006/105640821-2a6d3100-5e91-11eb-9afd-4d40f086e0e5.jpg)


For me what has become worse is the choice of the mode in resolution 4x3, it's just awful
![20210124220648_1](https://user-images.githubusercontent.com/32390006/105640812-1f1a0580-5e91-11eb-96b4-35c6f6f836fb.jpg)

**Comment by CriticalFlaw** [comment]
@johnRivs You can go back to the default health indicator by removing `flawhud/resource/ui/spectatorguihealth.res` and any line in `flawhud/scripts/hudanimations_custom.txt` that reference **GuiPlayerHealth**. The only issue is that the health on the TargetID will no longer display correctly as shown in the screenshot below. That's because the TargetID is not designed to fit the size of the default health indicator. 

![20210124201905_1](https://user-images.githubusercontent.com/6818236/105650330-79ab6580-5e81-11eb-92c6-0c29245c2ffb.jpg)

**Comment by CriticalFlaw** [comment]
@h9lk I don't see the issue with how the floating health is shown over the players' heads, it's readable and large enough to see. If you want it disabled, you can do so in the Advanced Options menu.

Regarding the mode selection, it's been fixed for 4:3 to display all four options as it did not do so before. The text being shown is known but won't be fixed because it's needed to fill space in higher resolutions. In all honesty, I think playing in 4:3 is silly and the HUD is not made with that resolution in mind.

![image](https://user-images.githubusercontent.com/6818236/105650524-fc342500-5e81-11eb-9543-fb0d58edeb19.png)

**Comment by h9lk** [comment]
> I don't see the issue with how the floating health is shown over the players' heads, it's readable and large enough to see. If you want it disabled, you can do so in the Advanced Options menu.
> 
> Regarding the mode selection, it's been fixed for 4:3 to display all four options as it did not do so before. The text being shown is known but won't be fixed because it's needed to fill space in higher resolutions. In all honesty, I think playing in 4:3 is silly and the HUD is not made with that resolution in mind.

@CriticalFlaw question is more directed to author of post, it was my mistake that didn't pose @, think this is the most convenient display and see no reason to change it, was interested in opinion of a person why he wants to return this mapping to this fat plus above pocket head.

Regarding the expansion, don't use this hud, as it's not comfortable for me at 6s, in this extension can see everything perfectly.  But fact that this extension can't create server or select training mode - sad

**Comment by johnRivs** [comment]
@CriticalFlaw That works for me, thank you. You think I can also change the text color inside the cross? Something darker so it contrasts better with the beige.

**Comment by CriticalFlaw** [comment]
@johnRivs For that, instead of deleting `flawhud/resource/ui/spectatorguihealth.res` you could replace all of its contents to what's being used in the default HUD (linked below), then go to `PlayerStatusHealthValue` and change the `fgcolor` from TanDark to White or TanLight or whatever works for you.

https://raw.githubusercontent.com/Hypnootize/TF2-Default-Hud/710492de20779d3568f1f4d50ffcd7ed7cd00a82/resource/ui/spectatorguihealth.res

**Comment by CriticalFlaw** [comment]
@h9lk I understand, it's all good. Also just FYI, the Training and Create Server buttons were moved to the icon tray just above the Friends List because they didn't fit on the Mode Selection panel in 4:3

**Comment by johnRivs** [comment]
@CriticalFlaw  Works for the one above the player. Is it possible to change the text color for the cross in the bottom?
![](https://i.imgur.com/WzHxoNa.png)

**Comment by CriticalFlaw** [comment]
@johnRivs Try changing `TextColor` in `resource/ui/targetid.res` under `SpectatorGUIHealth`

![image](https://user-images.githubusercontent.com/6818236/106394722-0303f000-63cc-11eb-95e5-d40ce2fc586b.png)

**Comment by johnRivs** [comment]
@CriticalFlaw Doesn't quite work. I'll set it to "Black" or "Red" or anything else, I refresh the HUD, it'll show black (for "Red" too) but when I heal someone else it'll go back to white.

**Comment by CriticalFlaw** [comment]
@johnRivs Did you also make sure change the FgColor from HudWhite under `HudHealthBonusPulseStop` and `HudHealthDyingPulseStop` in `scripts/hudanimations_custom.txt`? Those are the animations that change the color when healing or being healed or damaged.

**Comment by johnRivs** [comment]
@CriticalFlaw I've got these things:
`TextColor` `Black` under `SpectatorGUIHealth` in `targetid.res`
`fgcolor` `Black` under `PlayerStatusHealthValue` in `spectatorguihealth.res`
`FgColor` `Black` next under `HudHealthBonusPulseStop` and `HudHealthBonusPulseStop`

When everything is black, it works but it'll change my own health to black. When I set `PlayerStatusHealthValue` under `HudHealthBonusPulseStop` and `HudHealthBonusPulseStop` to `HudWhite`, both my HP and the one in between my HP and ammo stay white.

One thing gets fixed, another one gets broken haha :P

**Comment by CriticalFlaw** [comment]
Under `HudHealthBonusPulseStop` and `HudHealthBonusPulseStop` revert `PlayerStatusHealthValue` back to HudWhite. I think that's the only variable that colors your health so you probably don't want to appear black.

**Comment by johnRivs** [comment]
Yeah but that's also the one making my target's HP white.
![](https://i.imgur.com/ntamk0D.png)
![](https://i.imgur.com/cVb6Nrj.png)

**Comment by CriticalFlaw** [comment]
`spectatorguihealth.res` shouldn't have `PlayerStatusHealthValue` - it should be using `GuiPlayerHealth` which you would want to color in animations instead.
![image](https://user-images.githubusercontent.com/6818236/106488518-ca265280-6481-11eb-9eb8-bb93de4c973a.png)

**Comment by johnRivs** [comment]
Got it 😭 I'll live with the weirdly shaped cross up there. Thank you for your time!
![](https://i.imgur.com/ljBOyEH.png)

**Comment by CriticalFlaw** [comment]
No problem at all. Closing the ticket now.
