### ISSUE TITLE
Badges on the scoreboard are misaligned and CP indicator is missing

### ISSUE THREAD

**Issue by scarface52** [CriticalFlaw/flawhud#156]
After installing the latest version of the flawhud, badges on the scoreboard now look like this.
![20210530172307_1](https://user-images.githubusercontent.com/71343424/120117070-19f8fa00-c194-11eb-8806-da0dd4f9be42.jpg)

On CP and KOTH gamemode hud element that appears below-mid of the screen is missing.
![20210530221538_1](https://user-images.githubusercontent.com/71343424/120117300-3d707480-c195-11eb-95a1-6a755929d0aa.jpg)

I have installed the new version after deleting the old one. Not sure if I missed anything.

**Comment by CriticalFlaw** [comment]
Does this happen every time or only sometimes? Also, next time this happens try entering `hud_reloadscheme` into console or use the Refresh HUD button in the HUD Options and see if that fixes things.

**Comment by scarface52** [comment]
Yes, it happens every time and I have used that option but it didn't help.

**Comment by CriticalFlaw** [comment]
I'll take a look later tonight. Thank you for reporting it.

**Comment by CriticalFlaw** [comment]
The bug was being caused by a recent change where the player list was being pinned to its background using `pin_to_sibling`. For whatever reason, casual badges' position gets messed up when using that property. The bug has been fixed here: b164ef1277f38a15ed5a6d92db5bced6d508ce21.

Please verify and then close the ticket if it looks good. Cheers.

![20210530223740_1](https://user-images.githubusercontent.com/6818236/120132083-b244ae00-c197-11eb-8136-8f2806af86f2.jpg)

**Comment by CriticalFlaw** [comment]
I wasn't able to replicate the issue with control point icons not displaying. Could be an issue caused by a different mod if you have one installed. Otherwise, this is likely just an occasional game bug. 

![20210530223737_1](https://user-images.githubusercontent.com/6818236/120132089-b5d83500-c197-11eb-95cb-6b4d16267cbc.jpg)

**Comment by scarface52** [comment]
The issue related to badges has been fixed, thank you.

The control point indicator issue is somehow disappeared. Perhaps it was an occasional game bug like you said.
