### ISSUE TITLE
Match death outlines wrong team colors

### ISSUE THREAD

**Issue by Silexos** [CriticalFlaw/flawhud#157]
Hiyo I noticed that dead team members will have the wrong team color for their background at the top of the screen. This doesn't seem to affect the player themself. The error continues upon refreshing the hud and reinstall.

![20210530193643_1](https://user-images.githubusercontent.com/85089160/120132514-53733a80-c17f-11eb-8127-adeab4cf5df4.jpg)

**Comment by CriticalFlaw** [comment]
Good catch. Fixed the issue in 3f428b755570d953ee2fecd67345d606f648c82d. Could you retest it please?

**Comment by Silexos** [comment]
Just tested it and it's working as intended! Thanks for the quick fix!

**Comment by Silexos** [comment]
I noticed that the team health values at the top of the screen does not change color in response to the changed values in the hud editor. It's minor but I figured I would mention it (also sorry if this came off as nitpicky I'm just hoping this feedback helps with your development).

**Comment by CriticalFlaw** [comment]
I'll make that change as well since users will probably expect that to change color if they use the editor. Thanks! 8d2ed3435e07a6d56660f1b0e763a40bd32aed9f

---

To give you some context, originally those colors were being referenced by their client scheme name instead of color code. That was changed to just color codes in 3cd3a48620112e62851048fded53415b764be966 because myself and Whisker had a theory that constant calls to the client scheme played a part in tanking performance. In my benchmark tests flawhud would go down by 5-8 FPS with the match hud enabled.

Similar tests with other huds on other machines didn't yield similar results, but I left the color codes in anyway. It's been added back now so if you could verify and if it looks good, close the ticket please.

**Comment by Silexos** [comment]
Alrighty! I didn't know how it worked so it was interesting to see you explain it a bit. It works great and the ticket has been closed, thanks again!
