### ISSUE TITLE
Icons not displaying on Linux/macOS

### ISSUE THREAD

**Issue by Rattlewrench** [CriticalFlaw/flawhud#16]
Some icons aren't being rendered correctly (at least under Linux distros). I'd take a wild guess that some font is missing, but I'm not sure.

1) Dropdown arrows
![](https://i.imgur.com/8UDfk36.png)
2) Also dropdown arrows
![](https://i.imgur.com/VrANWQ6.png)
3) Close icon, scrollbar arrows and resize corner
![](https://i.imgur.com/YDhFENv.png)
4) Check marks in the Play menu
![](https://i.imgur.com/eWG9wKI.png)
5) Check mark in the options
![](https://i.imgur.com/PjFq6cT.png)

**Comment by CriticalFlaw** [comment]
It must be an issue with Linux not rendering a font correctly, which font it is I can't say because for example in the first screenshot, the button to open the drop down list does not have a font associated with it in the code:

![image](https://user-images.githubusercontent.com/6818236/32179345-8fa08868-bd65-11e7-8b4a-1a1f1e627e9e.png)

I'll continue looking into it, but if anyone who has experience with Linux has any insight or a fix for this, they are welcome to contribute to this.

**Comment by Phraqzy** [comment]
Still have this problem

**Comment by CriticalFlaw** [comment]
I don't have access to a Linux machine, so somebody else would need to try and fix it

**Comment by Phraqzy** [comment]
I could help you but I don't have any knowledge about editing the files

**Comment by CriticalFlaw** [comment]
This has been fixed and will be included in the next update

**Comment by CriticalFlaw** [comment]
The fix has been added in https://github.com/CriticalFlaw/flawhud/commit/d5e10bf20a50467d3df8084ff176efffd9dbcd8d Please download the latest version from the master branch and retest. If it's fixed on your end then please close the the ticket.

**Comment by Rattlewrench** [comment]
Yep, seems to be completely fixed. Nice job!
