### ISSUE TITLE
Engineer metal status blocks chat when using alternate hud/lowered chatbox

### ISSUE THREAD

**Issue by shaiico** [CriticalFlaw/flawhud#206]
When using the alternate hud and lowered chatbox, the engineer metal status blocks some of the chat, which makes it difficult to read. This can be remedied by modifying the `hudaccountpanel.res` file and adjusting the metal status y-position.

**Current build:**

![Current Build](https://i.imgur.com/0hG8Rbp.png)

**Proposed fix:**

![Proposed Fix](https://i.imgur.com/nry7Ql7.png)

```
	"CHudAccountPanel"
	{
		"delta_item_x"			"30"
		"delta_item_start_y"	"50"
		"delta_item_end_y"		"40"
		"PositiveColor"			"0 170 127 255"
		"NegativeColor"			"190 20 20 200"
		"delta_lifetime"		"1.15"
		"delta_item_font"		"FontBold22"
	}
```
```
	"MetalIcon"
	{
		"ControlName"			"CIconPanel"
		"fieldName"				"MetalIcon"
		"xpos"					"15"
		"ypos"					"70"
		"zpos"					"1"
		"wide"					"10"
		"tall"					"10"
		"visible"				"1"
		"enabled"				"1"
		"scaleImage"			"1"
		"icon"					"ico_metal"
	}
```
```
	"AccountValue"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"AccountValue"
		"xpos"					"26"
		"ypos"					"65"
		"zpos"					"2"
		"wide"					"50"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"2"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"labelText"				"%metal%"
		"textAlignment"			"center"
		"dulltext"				"0"
		"brighttext"			"0"
		"font"					"FontBold22"
	}
```

**Comment by CriticalFlaw** [comment]
Similar to https://github.com/CriticalFlaw/flawhud/issues/205 the issue is caused by the "Lower In-Game Chat" option in the editor takes priority over other customization options that also move the chat. The solution would be to have the position of the achievement tracker, building, metal and chat be controlled by the lower in game chat option instead of HUD Layout.

You can probably close #205 in favor of keeping this one open

**Comment by shaiico** [comment]
Thanks for the suggestion. I closed #205. That sounds like a better solution. I assumed that by ticking the lower in game chat option, it was making a modification to the hud layout file, hence my idea.

**Comment by CriticalFlaw** [comment]
You're correct. Because both options modify hudlayout for their needs, only the latter option's changes will actually take effect overwriting what came before it.

Therefore elements on the left side of the screen where regardless of the chat and hud layout option selected, it will always look good. I'll look more into that in these coming days.

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/TF2HUD.Editor/commit/d03a730abf57629653ae7cb6fea793b34cdc6c87. The metal counter is now going to be above the ammo while the lower-chat option swaps achievement tracker and chat positions. Regardless of the which options you choose it should look good without any overlaps.
