### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#213]
Licenses are important. You should have one.

Read here about what happens when you don't have a license: https://choosealicense.com/no-permission/

I recommend the MIT License. You can read more about the other licenses here: https://choosealicense.com/licenses/

**Comment by CriticalFlaw** [comment]
Normally I'd agree but because this HUD is not a piece of software in a traditional sense, I don't really see the point or reason of adding a license. If someone takes this project and modifies or redistributes it elsewhere without permission or credit, I don't really care nor do I have the time to chase them down.

flawhud has been around for long enough that people within the community would catch and report them without my involvement. This already happened a few times on GameBanana where a close copy of flawhud was reuploaded without credit or permission. It's against their rules I think but people know where to find the official copy of the project so there's no issue.

Thank you for the suggestion.
