### ISSUE TITLE
Revert changes to mode selection

### ISSUE THREAD

**Issue by chelIey** [CriticalFlaw/flawhud#229]
the mode selection tab in the newest TF2 HUD editor version seems to be bugged. 
https://ibb.co/pKK4qzF <- last version from github
https://ibb.co/R6YcwDY < - newest HUD editor ver
the buttons and the images are all swapped around, although it seems that the buttons function as the text indicates

unless this is some kind of joke about how casual is bot infested, but I don't really appreciate that becuase I still mainly use casual and I think this layout sucks visually. so if it is I would rather it be an option because trying to get my preferred custom settings by rummaging through files I don't understand is not my favourite

**Comment by CriticalFlaw** [comment]
The change was intentional because Casual was/is unplayable in its current state, so it made little sense to make it the most prominent game mode option. In any case, I've had my fun and reverted it back to the way it was: f92c8a27c1ae86fc179652259b1437d78abb067d

Remember to support your community servers.
