### ISSUE TITLE
Feature request: keep MVM end screen title in uppercase

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#251]
Default HUD: "BIGROCK : **BOMBANDO FURTIVAMENTE**"
![image](https://user-images.githubusercontent.com/30274161/197663101-ef1a7650-f142-4b2e-b0a6-33dc56439513.png)

FlawHUD: "BIGROCK : **Bombando Furtivamente**" (please ignore the highlighted part in red)
![image](https://user-images.githubusercontent.com/30274161/197663131-49c9c298-d17b-44d9-b061-2dfe87669dcc.png)

**Comment by CriticalFlaw** [comment]
In the default HUD it's all uppercase because the TF2 Build does not do lowercase, same as with the default flawhud setup.

To address this, the below file would have to be added and the labels `HeaderLabel`, `HeaderShadow` would have to be updated to include `"wrap" "1"` to force that text to be in uppercase. Because this is a niche request that's only effecting Code Pro users I don't feel like it's worth adding this file to the main branch. You may try adding the file and making the change manually if you'd like. Thanks.

https://raw.githubusercontent.com/Hypnootize/TF2-Default-HUD/master/resource/ui/mvmvictorypanel.res
