### ISSUE TITLE
Move Chat to the Bottom should be default

### ISSUE THREAD

**Issue by ThatGreenBlur** [CriticalFlaw/flawhud#255]
I think the customization "Move Chat to the Bottom" should be default because the default hud has similar chat position and its a more popular position. the top left chat position should be the optional customization instead

**Comment by CriticalFlaw** [comment]
Thank you for the suggestion. I've gone back and forth on this over the years but being at the top ended up being the best spot for it because of the Engineer's buildings and tournament spectator, which the chat does not accommodate if it is positioned near the bottom.

I think with the editor it can be up to the individual to set it to whatever they want.

**Comment by ThatGreenBlur** [comment]
alright, that makes sense, thanks!
