### ISSUE TITLE
Misaligned Shield Charge Meter

### ISSUE THREAD

**Issue by MA113822** [CriticalFlaw/flawhud#289]
The shield charge meter is raised higher up than it should be, which also has the side effect of obscuring player names
![20230119154834_1](https://user-images.githubusercontent.com/114884081/213557141-fff2da4b-909f-40f8-b2b2-32e343bdfabc.jpg)
![20230119154824_1](https://user-images.githubusercontent.com/114884081/213557155-6de007f2-e7b0-40e8-b9c0-7de99ee7b654.jpg)

**Comment by CriticalFlaw** [comment]
Is your version of flawhud installed via the editor or downloaded from somewhere?

**Comment by Metisz** [comment]
> Is your version of flawhud installed via the editor or downloaded from somewhere?

Probably the editor, had basically the same thing happen to me there

**Comment by MA113822** [comment]
yeah, I installed this with the editor, it might be that

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/flawhud/commit/339967cdc5ccd7aaeade9490712ea30c361c995c and also updated the editor schema to match.

If you're not using the editor, attached is the flawhud with the fix and centered layout. Cheers.
[flawhud.zip](https://github.com/CriticalFlaw/flawhud/files/10471533/flawhud.zip)
