### ISSUE TITLE
[BUG] Overtime text off center

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#322]
![image](https://user-images.githubusercontent.com/123919000/232916390-37791183-58e5-4761-9b4f-d60e8656da0e.png)

The overtime text at the top of the screen under the timer is off center while I was playing dustbowl, I have only noticed this once so far so idk if its a bug or a game issue but ill keep check

EDIT:
![image](https://user-images.githubusercontent.com/123919000/232962974-f194ca01-a296-402b-a842-f8d38fc0a18c.png)

Yep, just tested again in a private server and the issue is still present with the overtime text being off center, so is most likely to be a hud issue

**Comment by CriticalFlaw** [comment]
This happens because of how in KOTH the overtime label can appear on either team's side if both are happened to be competing in overtime. I've seen this before but wasn't quite able to find a proper fix for it without breaking something else.

I'll leave this open for anyone else to take a gander at it.
