### ISSUE TITLE
Minor issue with scoreboard

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#331]
![image](https://github.com/CriticalFlaw/flawhud/assets/123919000/6f0a7879-1654-4359-aa4f-03a1a5e342fe)

This is kinda hard to explain but when for example the 24 player scoreboard is full with a team of 12 players, when a 13th player joins  the team half their name on the scoreboard is going out the box on the scoreboard, the transparent gray background behind the players (may be hard to see) is also going outside the box when a 13th player joins a team

Since the scoreboard is full, the name shouldnt appear at all until you scroll down the list

This also happens on 32 player scoreboards when a 17th player joins a team

This issue is hard to put into words so I put an image, hopefully that visualizes things

**Comment by CriticalFlaw** [comment]
The cutoff is partially caused by having the slider enabled and your resolution.

There's no optimal settings where the names are not cut off unless the list font is condensed (like in the default hud) which I do not plan on doing.

**Comment by CriticalFlaw** [comment]
Just retested looks fine with and without the sliders being enabled (_Enable mouse input on the scoreboard_ in Advanced Options). The slight cutoff could either be because the slider is lower or just a quirk with a particular resolution. In any case I won't be making any changes.

![20230525211432_1](https://github.com/CriticalFlaw/flawhud/assets/6818236/13e6dd79-4c43-4580-8143-64d40a7f2eb7)
![20230525211649_1](https://github.com/CriticalFlaw/flawhud/assets/6818236/8182c9e7-4a9c-46a8-aa11-728437b0f076)
