### ISSUE TITLE
Captions overlapping with ammo

### ISSUE THREAD

**Issue by Dragonissa** [CriticalFlaw/flawhud#358]
Version: v2023.0730
Screen resolution: 2560x1600 (16:10)

![image](https://github.com/CriticalFlaw/flawhud/assets/4233773/a923787a-16c6-4296-ace5-41102def5426)

**Comment by CriticalFlaw** [comment]
This looks to be an issue with a 16:10 resolution specifically. Because when I tested with 16:9 (3440x1440 and 1920x1080) the closed captions have enough away from the ammo to not overlap.

![20230730161109_1](https://github.com/CriticalFlaw/flawhud/assets/6818236/7609407b-ba86-45d5-8b4f-cbe246dfca18)

I've adjusted the values for closed captions slightly to see if it can mitigate the issue you're having while not impacting the rest. Let me know what you think.

**Comment by Dragonissa** [comment]
Looks a bit better. Maybe another fix for the Editor to enable 16:10 mode?
Idk if there is some way to change those values based on booleans?

![image](https://github.com/CriticalFlaw/flawhud/assets/4233773/dd702879-bb81-4bb5-a50b-8995d674036f)

**Comment by Dragonissa** [comment]
![image](https://github.com/CriticalFlaw/flawhud/assets/4233773/fcf85874-0fdb-4edf-9a44-058ed03a2e67)

Ive changed it to the following which hasnt caused issues so far. I've only noticed its overlapping with the equipment preview in spectator, though im not sure its thats also just an issue because of 16:10.
```
"xpos"	"r120"
"ypos"	"r300"
"wide"	"115"
"tall"	"200"
```
