### ISSUE TITLE
[flawhud] Chat overlapping with vote screen

### ISSUE THREAD

**Issue by Dragonissa** [CriticalFlaw/flawhud#369]
Version: v2023.0730
Screen resolution: 2560x1600 (16:10)

- Using the option for the lower chat. 

I assume that's the issue why its overlapping. Is there any way to move the vote screen further up instead?

![image](https://github.com/CriticalFlaw/flawhud/assets/4233773/c72f2229-48af-4d00-a086-7ad820c8ac8f)

<img width="316" alt="Screenshot_1" src="https://github.com/CriticalFlaw/flawhud/assets/4233773/2b9d3674-e9fa-4c72-a988-22dee8c1fad6">
<img width="433" alt="Screenshot_2" src="https://github.com/CriticalFlaw/flawhud/assets/4233773/921dfcb0-177d-4e47-8afa-185eba6f9d49">

**Comment by CriticalFlaw** [comment]
The issue is that whichever way you move the chat or vote panel it will then overlap the building or achievement tracker.

![image](https://github.com/CriticalFlaw/flawhud/assets/6818236/ff92eaea-3ced-4200-a466-980bd0a400d3)

That's why the default layout is usually best, but I'll see what other values could balance all elements out. I'll also transfer this to the editor repo since it's not somethng to be fixed with hud files imo.

**Comment by Dragonissa** [comment]
Right, i forgot that buildings are up there and achievements down there (never had those on my hud). Thanks.

**Comment by CriticalFlaw** [comment]
16:10 specific customizations could be added. But I'd need a 16:10 monitor to really create it. Unless someone else wants to do it

**Comment by Dragonissa** [comment]
I could possible help testing them or try changing it myself? Depends on what would needed to be changed (this for example https://github.com/CriticalFlaw/flawhud/issues/358)

**Comment by CriticalFlaw** [comment]
It'd be easier if someone submitted a pull request with all the changes for 16:10 that could then either be merged in if they don't cause any issues for other resolutions or made into an editor option.

**Comment by CriticalFlaw** [comment]
Should be fixed in 69fdeb7ce62f2f8a87945157d17b473bf59e783f.

I updated the customization to move the achievement tracker up if the chat is lowered. Also move the achievement tracker and Engineer's buildings. When customizing they may not always gel well together but for majority of use cases this should be fine.
