### ISSUE TITLE
Health ID Needs A Visible Cross

### ISSUE THREAD

**Issue by floofycatto** [CriticalFlaw/flawhud#370]
As a medic main using this hud, it's very difficult to determine someone's health with just numbers alone, I suggest having the option to replace the heal target ID text with the vanilla old cross

The current health ID system is fine but there's room for more vital info to be shown, when a class is overhealed, the current numbers could simply turn green, and when at half health, the text could appear

A simple but effective fix

**Comment by CriticalFlaw** [comment]
Adding a proper health cross to the targetId would require a lot of changes to the targetId due to a height restraint. Basically the targetID must be low to the bottom of the alloted space to have a thin team color strip at the bottom. The health cross will appear half cut off as a result.

I'm not sure I understood the second point, the health value on the targetId already turns green when overhealed and red when under half. Are you suggesting to color the background instead?

**Comment by floofycatto** [comment]
Hi! Thanks for the reply! It's completely okay if you can't add the cross,

But to be more clear about the issue I'm talking about in the 2nd part, in this picture right here this scout is overhealed, but the color remains the same, this is mostly when you have your crosshair on your teammate, the color doesnt change, it's the same for when they're low too, this may feel like a little nickpick but for me when I load up into a real match, I feel like I could not be prioritizing my targets well enough, and having this extra quick glance color coded health mechanic could potentially be the difference between my teammate dying or living, on a side not I feel like adding a black background behind the health above their head could help with number reading, maybe give it an opacity of 50-75 too

![image](https://github.com/CriticalFlaw/flawhud/assets/86273332/cba52e9d-c6e0-4c09-8b18-4e57c8ea2028)
![image](https://github.com/CriticalFlaw/flawhud/assets/86273332/2f378b9b-b49f-4b70-a6a1-cd9fb0ccd761)

**Comment by CriticalFlaw** [comment]
Ah I see, the health value is colored when displaying the player health on the TargetID (In Advanced Options, there's an option to disable floating health on the targetID). I'll check if it's possible to color the floating health (no reason not to be but I'll double check)

**Comment by CriticalFlaw** [comment]
This looks to be a game bug of some sort because the floating health value (TargetHealthValue in `flawhud/resouce/ui/spectatorguihealth.res`) has animations to turn green or red when buffed or hurt but they don't seem to play out. The same TargetHealthValue is used in the TargetID and in Tournament Spectator but they work as expected.

Floating Health Disabled
![20230805164641_1](https://github.com/CriticalFlaw/flawhud/assets/6818236/cee0a757-6531-4978-b07e-0dd5cdfe3784)

Floating Health Enabled
![20230805164644_1](https://github.com/CriticalFlaw/flawhud/assets/6818236/9c199969-678d-4e73-84f0-13b072a433b6)

**Comment by floofycatto** [comment]
So to my understanding this bug is a bug with TF2 itself and not the hud, making it unavailable to fix?

**Comment by CriticalFlaw** [comment]
Correct.
