### ISSUE TITLE
Halloween: The "Truce!" panel gets overlapped by the boss health bar

### ISSUE THREAD

**Issue by Kruphixx** [CriticalFlaw/flawhud#421]
Note: This only happens when the player is alive, not spectating. I hope this isn't something that's hardcoded?
Resolution: 1920x1080

![20231016190446_1](https://github.com/CriticalFlaw/flawhud/assets/50501742/da6700e9-1a16-4b71-ab43-e31b3f707a85)
![20231016190730_1](https://github.com/CriticalFlaw/flawhud/assets/50501742/5933b0ee-b1e9-46b1-b136-9c637b5b3065)

**Comment by CriticalFlaw** [comment]
It looks to be hardcoded depending on whether you're alive or not: https://github.com/mastercomfig/tf2-patches/blob/adce75185fe5822309f356424ea449dee029e2d8/src/game/client/tf/tf_hud_boss_health.h#L40

Though I guess that only applies to when you're dead because the boss health was moved in the past.

**Comment by Kruphixx** [comment]
Perhaps moving the boss health bar up a bit could work?

**Comment by CriticalFlaw** [comment]
It will then overlap with the respawn timer.

**Comment by Kruphixx** [comment]
Ah I guess there's no fixing this then.
