### ISSUE TITLE
Crasher-specific objective is off-center

### ISSUE THREAD

**Issue by Platina6978** [CriticalFlaw/flawhud#424]
See the screenshot attached below. The little icon with the gate indicating the objective on crasher is quite off-center with the circle HUD-element its in.

![20231029191355_1](https://github.com/CriticalFlaw/flawhud/assets/71837773/89949048-8241-4aa4-9f32-4f65645aefca)

**Comment by CriticalFlaw** [comment]
It turns out both the crasher and base CTF maps refer to the same location for their flag placement. Unforunately moving up the crasher flag will move the CTF briefcase out of the compass. Ideally crasher would have its own `if_` flag like Doomsday and certcai hybrid maps. Until then this will not be fixed. Sorry.

https://github.com/CriticalFlaw/flawhud/blob/master/resource/ui/hudobjectiveflagpanel.res#L288
