### ISSUE TITLE
Broken Tournament Spectator mode

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#92]
[Screenshot](https://i.imgur.com/8TIUKnl.jpg). This is not supposed to happen. All players (including RED players) were listed as BLU players ([screenshot proof](https://i.imgur.com/lYpjk2K.jpg)), and also the gamemode was Arena. The Tournament Spectator mode should only be activated when spectating a competitive match (like a 6v6 match for example).

**Comment by CriticalFlaw** [comment]
Normally the game would recognize that the player has switched teams and move their player panel to the side (this can be seen when viewing a demo of a competitive match), but since this is a custom game mode with it's own logic for changing a player's team it breaks the tournament spectator UI. Therefore this issue won't be fixed, especially since there's nothing I can do on my side to account for it.

Also Tournament Spectator is shown only if the server has tournament mode enabled, which is likely the case here.

**Comment by Perkzitos** [comment]
> Normally the game would recognize that the player has switched teams and move their player panel to the side (this can be seen when viewing a demo of a competitive match), but since this is a custom game mode with it's own logic for changing a player's team it breaks the tournament spectator UI. Therefore this issue won't be fixed, especially since there's nothing I can do on my side to account for it.
> 
> Also Tournament Spectator is shown only if the server has tournament mode enabled, which is likely the case here.

The server doesn't have it enabled, but I am using `cl_use_tournament_specgui 1`. Does this interfere?
